<h3 style="text-align: center;">EXPERIMENT-10</h3>
<h3 style="text-align: center;">Linear Convolution using DFT(Overlap-add & Overlap-save
methods)
</h3>

##### DATE: 10/11/23

##### AIM:
To simulate linear convolution of two signals using overlap add and overlap save methods.


##### SOFTWARE USED:
Python

##### THEORY:
Generally in discrete-time processing we talk about linearly convolving a sequence with a FIR filter. In contrast, the FFT performs circular convolution with a filter of equal or lesser length. In computing the DFT or FFT we often have to make linear convolution behave like circular convolution or vice versa. Two methods that make linear convolution look like circular convolution are overlap-add and overlap-save.

1. Overlap-Add Method :
This procedure cuts the signal up into equal length segments with no overlap. Then it zero-pads
the segments and takes the DFT of the segments. Part of the convolution result corresponds to
the circular convolution. The tails that do not correspond to the circular convolution are added to
the adjoining tail of the previous and subsequent sequence. This addition results in the aliasing
that occurs in circular convolution.

2. Overlap-Save Method:
This procedure cuts the signal up into equal length segments with some overlap. Then it takes
the DFT of the segments and saves the parts of the convolution that correspond to the circular
convolution. Because there are overlapping sections, it is like the input is copied therefore there
is no lost information in throwing away parts of the linear convolution.


##### CODE:

In [1]:
#Overlap Add method
import numpy as np 
xn = np.array(list(map(int, input('Enter Input signal: ').split(','))))
hn = np.array(list(map(int, input('Enter Impulse response: ').split(','))))
print(xn,hn)
hnlen = len(hn)
if len(xn)>=len(hn):
    m = len(hn)
    n = int(input('Enter length of each divided array (n): '))
    # n = 2**m
    l = n - m + 1
    hn = np.pad(hn, (0, l - 1))
    i = 0
    newarray = []
    while(i <= len(xn)):
        j = 0
        temp1 = [xn[j] for j in range(i,l+i) if j<len(xn)]
        # if l+i <= len(xn): 
        temp1 = np.pad(temp1, (0, m - 1))
        if len(temp1) < l + m - 1 and len(temp1)!=0: 
            temp1 = np.pad(temp1, (0, l + m - 1 - len(temp1)))
            # print(temp1)
        newarray.append(np.array(temp1))
        i = i + l
    # print(newarray)
    newarray = np.array(newarray)
    print(newarray)
    solutionarray = []
    i = 0
    j = 0
    row = l + m - 1
    column = l + m - 1
    while(i <= len(xn)):
        # print()
        if j<len(newarray):
            toeplitz = np.array(newarray[j])
            for a in range (len(newarray[j])- 1):
              newarray[j]= np.roll(newarray[j],1) #to cirular shift elements of array
              toeplitz = np.concatenate((toeplitz,newarray[j]))
            toeplitz.shape = (row,column)
            hn.shape = (row, 1)
            # print(hn.shape)
            # print(toeplitz)
            toeplitz = np.transpose(toeplitz)
            # print(toeplitz.shape)
            # print(toeplitz)
            temp = np.dot(toeplitz, hn)
            temp.shape = (row)
            # print(temp.shape)
            # x1 = np.fft.fft(newarray[j])
            # x2 = np.fft.fft(hn)
            # temp = np.fft.ifft(x1 * x2)
            # temp = np.convolve(newarray[j], hn)
            solutionarray.append(np.array(temp))
            j += 1
        i = i + l
    solutionarray = np.array(solutionarray)
    # print(hn)
    print(solutionarray)
    endarray = []
    for i in solutionarray: 
        for j in i:
            endarray.append(j)
    endarray = np.array(endarray)
    # print(endarray)
    for i in range(l, len(xn) + m - 1, l):
        # print()
        print(i)
        removedarray = endarray[i:i+2*(m-1)]
        # print(removedarray)
        endarray = np.delete(endarray, slice(i,i+2*(m-1)))
        # print(removedarray)
        part1 = removedarray[0:m-1]
        part2 = removedarray[m-1:2*(m-1)]
        # print(part1,part2)
        if len(part2)!=0: 
            result = np.add(part1,part2)
            endarray = np.insert(endarray, i, result)
    while(len(endarray)> len(xn) + hnlen - 1):
        endarray = np.delete(endarray, len(endarray) - 1)
        # print('dubic')
    print(endarray, len(endarray))
            
        
        
        

Enter Input signal:  3,2,6,1,8,4,6,9,7
Enter Impulse response:  2,1,3


[3 2 6 1 8 4 6 9 7] [2 1 3]


Enter length of each divided array (n):  4


[[3 2 0 0]
 [6 1 0 0]
 [8 4 0 0]
 [6 9 0 0]
 [7 0 0 0]]
[[ 6  7 11  6]
 [12  8 19  3]
 [16 16 28 12]
 [12 24 27 27]
 [14  7 21  0]]
2
4
6
8
10
[ 6  7 23 14 35 19 40 36 41 34] 10


In [2]:
import numpy as np 
xn = np.array(list(map(int, input('Enter Input signal: ').split(','))))
hn = np.array(list(map(int, input('Enter Impulse response: ').split(','))))
print(xn,hn)
if len(xn)>=len(hn):
    m = len(hn)
    n = int(input('Enter length of each divided array (n): '))
    # n = 2**m
    l = n - m + 1
    hn = np.pad(hn, (0, l - 1))
    i = 0
    newarray = []
    while(i <= len(xn)):
        # if l+i <= len(xn): 
        if i == 0 :
            temp1 = [xn[j] for j in range(i,l+i)]
            padded = np.zeros(m-1)
            for a in padded: 
                temp1 = np.insert(temp1, 0,a)
            # print(temp1)
        elif l+i<=len(xn):
            temp1 = [xn[j] for j in range(i+ 1,l+i)]
            padded = [xn[j-m] for j in range(i+m, i, -1)]
            for a in padded: 
                temp1 = np.insert(temp1, 0,a)
            # print(temp1)
        else: 
            if i==len(xn):
                break
            # print(i)
            temp1 = [xn[j] for j in range(i,len(xn))]
            # print(temp1)
            if j-m<len(xn):
                padded = [xn[j-m] for j in range(i+m-1, i, -1)]
                for a in padded: 
                    temp1 = np.insert(temp1, 0,a)
            temp1 = np.pad(temp1, (0, l + m - 1 - len(temp1)))
            # print(temp1)
        # print(temp1)
        newarray.append(np.array(temp1))
        i = i + l
    # print(newarray)
    newarray = np.array(newarray)
    print(newarray)
    convolvearray = []
    i = 0
    j = 0
    row = l + m - 1
    column = l + m - 1
    while(i <= len(xn)):
        # print()
        if j<len(newarray):
            toeplitz = np.array(newarray[j])
            for i in range (len(newarray[j])- 1):
              newarray[j]= np.roll(newarray[j],1) #to cirular shift elements of array
              toeplitz = np.concatenate((toeplitz,newarray[j]))
            toeplitz.shape = (row,column)
            hn.shape = (row, 1)
            # print(hn.shape)
            # print(toeplitz)
            toeplitz = np.transpose(toeplitz)
            # print(toeplitz.shape)
            # print(toeplitz)
            temp = np.dot(toeplitz, hn)
            temp.shape = (row)
            # print(temp.shape)
            # x1 = np.fft.fft(newarray[j])
            # x2 = np.fft.fft(hn)
            # temp = np.fft.ifft(x1 * x2)
            # temp = np.convolve(newarray[j], hn)
            convolvearray.append(np.array(temp))
            j += 1
        i = i + l
    convolvearray = np.array(convolvearray)
    # print(hn)
    print(convolvearray)
    endarray = []
    for i in convolvearray: 
        i = np.delete(i, slice(m-1))
        endarray.append(i)
    # print(endarray)
    answer = []
    for i in endarray: 
        for j in i:
            answer.append(j)
    answer = np.array(answer)
    print(answer)

Enter Input signal:  3,2,6,1,8,4,6,9,7
Enter Impulse response:  2,1,3


[3 2 6 1 8 4 6 9 7] [2 1 3]


Enter length of each divided array (n):  4


[[0 0 3 2]
 [3 2 6 1]
 [6 1 8 4]
 [8 4 6 9]
 [6 9 7 0]]
[[11  6  6  7]
 [25 10 23 14]
 [40 20 35 19]
 [43 43 40 36]
 [33 24 41 34]]
[ 6  7 23 14 35 19 40 36 41 34]


##### RESULT:
The linear convolution of two signals performed using overlap add and overlap save methods.
