In [1]:
#Overlap Add method
import numpy as np 
xn = np.array(list(map(int, input('Enter Input signal: ').split(','))))
hn = np.array(list(map(int, input('Enter Impulse response: ').split(','))))
print(xn,hn)
hnlen = len(hn)
if len(xn)>=len(hn):
    m = len(hn)
    n = int(input('Enter length of each divided array (n): '))
    # n = 2**m
    l = n - m + 1
    hn = np.pad(hn, (0, l - 1))
    i = 0
    newarray = []
    while(i <= len(xn)):
        j = 0
        temp1 = [xn[j] for j in range(i,l+i) if j<len(xn)]
        # if l+i <= len(xn): 
        temp1 = np.pad(temp1, (0, m - 1))
        if len(temp1) < l + m - 1 and len(temp1)!=0: 
            temp1 = np.pad(temp1, (0, l + m - 1 - len(temp1)))
            # print(temp1)
        newarray.append(np.array(temp1))
        i = i + l
    # print(newarray)
    newarray = np.array(newarray)
    print(newarray)
    solutionarray = []
    i = 0
    j = 0
    row = l + m - 1
    column = l + m - 1
    while(i <= len(xn)):
        # print()
        if j<len(newarray):
            toeplitz = np.array(newarray[j])
            for a in range (len(newarray[j])- 1):
              newarray[j]= np.roll(newarray[j],1) #to cirular shift elements of array
              toeplitz = np.concatenate((toeplitz,newarray[j]))
            toeplitz.shape = (row,column)
            hn.shape = (row, 1)
            # print(hn.shape)
            # print(toeplitz)
            toeplitz = np.transpose(toeplitz)
            # print(toeplitz.shape)
            # print(toeplitz)
            temp = np.dot(toeplitz, hn)
            temp.shape = (row)
            # print(temp.shape)
            # x1 = np.fft.fft(newarray[j])
            # x2 = np.fft.fft(hn)
            # temp = np.fft.ifft(x1 * x2)
            # temp = np.convolve(newarray[j], hn)
            solutionarray.append(np.array(temp))
            j += 1
        i = i + l
    solutionarray = np.array(solutionarray)
    # print(hn)
    print(solutionarray)
    endarray = []
    for i in solutionarray: 
        for j in i:
            endarray.append(j)
    endarray = np.array(endarray)
    # print(endarray)
    for i in range(l, len(xn) + m - 1, l):
        # print()
        print(i)
        removedarray = endarray[i:i+2*(m-1)]
        # print(removedarray)
        endarray = np.delete(endarray, slice(i,i+2*(m-1)))
        # print(removedarray)
        part1 = removedarray[0:m-1]
        part2 = removedarray[m-1:2*(m-1)]
        # print(part1,part2)
        result = np.add(part1,part2)
        endarray = np.insert(endarray, i, result)
    while(len(endarray)> len(xn) + hnlen - 1):
        endarray = np.delete(endarray, len(endarray) - 1)
        # print('dubic')
    print(endarray, len(endarray))
            
        
        
        

Enter Input signal:  1, 2, 3, 3, 2, 1, -1, -2, -3, 5, 6, -1, 2
Enter Impulse response:  3,2,1,1


[ 1  2  3  3  2  1 -1 -2 -3  5  6 -1  2] [3 2 1 1]


Enter length of each divided array (n):  7


[[ 1  2  3  3  0  0  0]
 [ 2  1 -1 -2  0  0  0]
 [-3  5  6 -1  0  0  0]
 [ 2  0  0  0  0  0  0]]
[[ 3  8 14 18 11  6  3]
 [ 6  7  1 -5 -4 -3 -2]
 [-9  9 25 11  9  5 -1]
 [ 6  4  2  2  0  0  0]]
4
8
12
[  3   8  14  18  17  13   4  -5 -13   6  23  11  15   9   1   2] 16


In [85]:
import numpy as np 
xn = np.array(list(map(int, input('Enter Input signal: ').split(','))))
hn = np.array(list(map(int, input('Enter Impulse response: ').split(','))))
print(xn,hn)
if len(xn)>=len(hn):
    m = len(hn)
    n = int(input('Enter length of each divided array (n): '))
    # n = 2**m
    l = n - m + 1
    hn = np.pad(hn, (0, l - 1))
    i = 0
    newarray = []
    while(i <= len(xn)):
        # if l+i <= len(xn): 
        if i == 0 :
            temp1 = [xn[j] for j in range(i,l+i)]
            padded = np.zeros(m-1)
            for a in padded: 
                temp1 = np.insert(temp1, 0,a)
            # print(temp1)
        elif l+i<=len(xn):
            temp1 = [xn[j] for j in range(i+ 1,l+i)]
            padded = [xn[j-m] for j in range(i+m, i, -1)]
            for a in padded: 
                temp1 = np.insert(temp1, 0,a)
            # print(temp1)
        else: 
            if i==len(xn):
                break
            # print(i)
            temp1 = [xn[j] for j in range(i,len(xn))]
            # print(temp1)
            if j-m<len(xn):
                padded = [xn[j-m] for j in range(i+m-1, i, -1)]
                for a in padded: 
                    temp1 = np.insert(temp1, 0,a)
            temp1 = np.pad(temp1, (0, l + m - 1 - len(temp1)))
            # print(temp1)
        # print(temp1)
        newarray.append(np.array(temp1))
        i = i + l
    # print(newarray)
    newarray = np.array(newarray)
    print(newarray)
    convolvearray = []
    i = 0
    j = 0
    row = l + m - 1
    column = l + m - 1
    while(i <= len(xn)):
        # print()
        if j<len(newarray):
            toeplitz = np.array(newarray[j])
            for i in range (len(newarray[j])- 1):
              newarray[j]= np.roll(newarray[j],1) #to cirular shift elements of array
              toeplitz = np.concatenate((toeplitz,newarray[j]))
            toeplitz.shape = (row,column)
            hn.shape = (row, 1)
            # print(hn.shape)
            # print(toeplitz)
            toeplitz = np.transpose(toeplitz)
            # print(toeplitz.shape)
            # print(toeplitz)
            temp = np.dot(toeplitz, hn)
            temp.shape = (row)
            # print(temp.shape)
            # x1 = np.fft.fft(newarray[j])
            # x2 = np.fft.fft(hn)
            # temp = np.fft.ifft(x1 * x2)
            # temp = np.convolve(newarray[j], hn)
            convolvearray.append(np.array(temp))
            j += 1
        i = i + l
    convolvearray = np.array(convolvearray)
    # print(hn)
    print(convolvearray)
    endarray = []
    for i in convolvearray: 
        i = np.delete(i, slice(m-1))
        endarray.append(i)
    # print(endarray)
    answer = []
    for i in endarray: 
        for j in i:
            answer.append(j)
    answer = np.array(answer)
    print(answer)

[ 1  2  3  3  2  1 -1 -2 -3  5  6 -1  2] [3 2 1 1]
[[ 0  0  0  1  2  3  3]
 [ 2  3  3  2  1 -1 -2]
 [ 1 -1 -2 -3  5  6 -1]
 [ 5  6 -1  2  0  0  0]]
[[ 11   6   3   3   8  14  18]
 [  2  10  15  17  13   4  -5]
 [ 12   4  -8 -13   6  23  11]
 [ 15  28  14  15   9   1   2]]
[  3   8  14  18  17  13   4  -5 -13   6  23  11  15   9   1   2]
